(***********************************************************************
This file was generated automatically by the Mathematica front end.
It contains Initialization cells from a Notebook file, which typically
will have the same name as this file except ending in ".nb" instead of
".m".

This file is intended to be loaded into the Mathematica kernel using
the package loading commands Get or Needs.  Doing so is equivalent to
using the Evaluate Initialiation Cells menu command in the front end.

DO NOT EDIT THIS FILE.  This entire file is regenerated automatically 
each time the parent Notebook file is saved in the Mathematica front end.
Any changes you make to this file will be overwritten.
***********************************************************************)

Clear[BuffonsNeedle];
BuffonsNeedle[n_,print_] :=
Block[{x, y, theta, a, b, total = 0, graphlist = {}},
	  (* box creates a graphics object on which the experiments are displayed *)
      box = Graphics[{Line[{{0,0},{10,0}}],  
                      Line[{{10,0},{10,10}}],
      		          Line[{{10,10},{0,10}}],
                      Line[{{0,10},{0,0}}],
                      Line[{{0,1},{10,1}}],
                      Line[{{0,2},{10,2}}],
                      Line[{{0,3},{10,3}}],
                      Line[{{0,4},{10,4}}],
                      Line[{{0,5},{10,5}}],
                      Line[{{0,6},{10,6}}],
                      Line[{{0,7},{10,7}}],
                      Line[{{0,8},{10,8}}],
                      Line[{{0,9},{10,9}}],
                      Line[{{0,10},{10,10}}]
                     }
                    ];  
	  For[i = 1, i <= n, i++,
	      x = Random[Real, {0,10}];      (*  Generates one endpoint with random coordinates.  *)
	      y = Random[Real, {0,10}];
	      theta = Random[Real, {0,2*Pi//N}];   (*  Generates a random angle for the orientation of the segment.  *)
	      endpts = {{x,y}, {x+Cos[theta], y+Sin[theta]}};  (* Computes the other endpoint. *)
	      a = Min[y, y+Sin[theta]];    (*  The next few statements determine whether the segment crosses one of the horizontal bars.  *)
	      b = Floor[Max[y,y+Sin[theta]]];
	      If[a <= b, total++];    (*  If the segment does cross a bar, total is increased by one.  *)
          If[(Mod[i,100] == 0)&&(print),   (*  Adds one line out of a hundred to the list to be displayed.  *)
	         graphlist = Append[graphlist, 
	      				        Graphics[Line[endpts]]
	      				       ]
	        ];
	     ];
	  If[print, Show[box, graphlist, AspectRatio->.95]];   (*  Displays final picture.  *)
	  Print["The simulated estimate for Pi is ", (2*n)/total//N, "."];
	 ]