(***********************************************************************
This file was generated automatically by the Mathematica front end.
It contains Initialization cells from a Notebook file, which typically
will have the same name as this file except ending in ".nb" instead of
".m".

This file is intended to be loaded into the Mathematica kernel using
the package loading commands Get or Needs.  Doing so is equivalent to
using the Evaluate Initialiation Cells menu command in the front end.

DO NOT EDIT THIS FILE.  This entire file is regenerated automatically 
each time the parent Notebook file is saved in the Mathematica front end.
Any changes you make to this file will be overwritten.
***********************************************************************)



Clear[montecarlo];
montecarlo[n_, f_, xmin_, xmax_, ymax_] :=
Block[{boxarea = ymax*(xmax - xmin),
       
(*  Because of a bug in the Mathematica function Random, we
    must first take numerical approximations to the input values
    xmin, xmax, and ymax.
*)
     
       nymax = N[ymax],
       nxmax = N[xmax],
       nxmin = N[xmin],
       count = 0,
       randpoint,
       pointlist = {}
       },
      For[i = 1, i <= n, i++,
          randpoint = {Random[Real, {nxmin, nxmax}],
                       Random[Real, {0, nymax}]
                      };
          pointlist = Append[pointlist, randpoint];
          If[(randpoint[[2]] <= f[randpoint[[1]]]), 
             count++
            ];
         ];
      Print[(count/n)*ymax*(xmax - xmin)//N];
      
(* In the following command, the first two graphics calls
are given the option DisplayFunction -> Identity so
that they are not plotted on the screen.  Then the Show
command is given the two plots with the DisplayFunction
option set back to the default value.  This results in
only one graph being shown on the screen, rather than
three.
*)

      Show[{Plot[f[x], {x, xmin, xmax},
            DisplayFunction -> Identity], 
            ListPlot[pointlist, DisplayFunction -> Identity]
           }, DisplayFunction -> $DisplayFunction,
           AspectRatio -> 1
          ];
     ]














