(***********************************************************************
This file was generated automatically by the Mathematica front end.
It contains Initialization cells from a Notebook file, which typically
will have the same name as this file except ending in ".nb" instead of
".m".

This file is intended to be loaded into the Mathematica kernel using
the package loading commands Get or Needs.  Doing so is equivalent to
using the Evaluate Initialiation Cells menu command in the front end.

DO NOT EDIT THIS FILE.  This entire file is regenerated automatically 
each time the parent Notebook file is saved in the Mathematica front end.
Any changes you make to this file will be overwritten.
***********************************************************************)



Clear[PowerCurve];
PowerCurve[n_, mlist_, nullp_, altp_, errormax_] :=
Block[{pmin = nullp - (Abs[altp - nullp]), 
       pmax = altp + (Abs[altp - nullp]),
       flist = {}
      },
      For[i = 1, i <= Length[mlist], i++,
          flist = Append[flist,
                         Plot[Sum[Bin[n, p, k], 
                                  {k, mlist[[i]], n}]
                             , {p, pmin, pmax},
                             DisplayFunction -> Identity
                             ]
                        ];
         ];   
      Show[Graphics[{Dashing[{0.03, 0.03}],
                     Line[{{nullp, errormax},
                          {altp, errormax}
                         }
                        ]
                   }],
           Graphics[{Dashing[{0.03, 0.03}],
                     Line[{{nullp, 1 - errormax},
                          {altp, 1 - errormax}
                         }
                        ]
                   }],
           Graphics[{Dashing[{0.03, 0.03}],
                     Line[{{nullp, errormax},
                          {nullp, 1 - errormax}
                         }
                        ]
                   }],
           Graphics[{Dashing[{0.03, 0.03}],
                     Line[{{altp, errormax},
                          {altp, 1 - errormax}
                         }
                        ]
                   }],
           flist, DisplayFunction -> $DisplayFunction,
           Axes -> True, PlotRange -> {0, 1}]
     ]



